/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TimelineDiaryPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  diaryFolder: "\u65E5\u8BB0",
  categories: [
    { name: "\u5DE5\u4F5C", color: "#3b82f6" },
    { name: "\u5B66\u4E60", color: "#10b981" },
    { name: "\u751F\u6D3B", color: "#f59e0b" },
    { name: "\u5A31\u4E50", color: "#ef4444" }
  ],
  uncategorizedColor: "#9ca3af",
  codeblockLang: "timeline"
};
var TimelineDiarySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u65F6\u95F4\u8F74\u65E5\u8BB0\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u65E5\u8BB0\u6587\u4EF6\u5939").setDesc("\u5B58\u653E\u65E5\u8BB0\u6587\u4EF6\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\uFF0C\u7528\u4E8E\u6C47\u603B\u7EDF\u8BA1").addText(
      (text) => text.setPlaceholder("\u65E5\u8BB0").setValue(this.plugin.settings.diaryFolder).onChange(async (value) => {
        this.plugin.settings.diaryFolder = value || "\u65E5\u8BB0";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u4EE3\u7801\u5757\u6807\u8BC6").setDesc("\u7528\u4E8E\u8BC6\u522B\u65F6\u95F4\u8F74\u7684\u4EE3\u7801\u5757\u8BED\u8A00\u6807\u8BC6").addText(
      (text) => text.setPlaceholder("timeline").setValue(this.plugin.settings.codeblockLang).onChange(async (value) => {
        this.plugin.settings.codeblockLang = value || "timeline";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u672A\u5206\u7C7B\u989C\u8272").setDesc("\u6CA1\u6709\u65F6\u95F4\u6807\u7B7E\u7684\u6761\u76EE\u9ED8\u8BA4\u663E\u793A\u7684\u989C\u8272").addColorPicker(
      (color) => color.setValue(this.plugin.settings.uncategorizedColor).onChange(async (value) => {
        this.plugin.settings.uncategorizedColor = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u4E8B\u4EF6\u7C7B\u578B" });
    containerEl.createEl("p", {
      text: "\u81EA\u5B9A\u4E49\u4E8B\u4EF6\u7C7B\u522B\u53CA\u5176\u5BF9\u5E94\u989C\u8272\u3002\u5728\u65E5\u8BB0\u4E2D\u4F7F\u7528 #\u7C7B\u522B\u540D \u6765\u6807\u8BB0\u4E8B\u4EF6\u3002",
      cls: "setting-item-description"
    });
    const categoriesContainer = containerEl.createDiv("timeline-diary-categories");
    this.renderCategories(categoriesContainer);
  }
  renderCategories(container) {
    container.empty();
    this.plugin.settings.categories.forEach((category, index) => {
      const row = container.createDiv("timeline-diary-category-row");
      const nameInput = row.createEl("input", {
        type: "text",
        placeholder: "\u7C7B\u522B\u540D\u79F0",
        value: category.name
      });
      nameInput.addEventListener("change", async () => {
        this.plugin.settings.categories[index].name = nameInput.value;
        await this.plugin.saveSettings();
      });
      const colorInput = row.createEl("input", {
        type: "color",
        value: category.color
      });
      colorInput.addEventListener("change", async () => {
        this.plugin.settings.categories[index].color = colorInput.value;
        await this.plugin.saveSettings();
      });
      const deleteBtn = row.createEl("button", {
        text: "\u5220\u9664"
      });
      deleteBtn.addEventListener("click", async () => {
        this.plugin.settings.categories.splice(index, 1);
        await this.plugin.saveSettings();
        this.renderCategories(container);
      });
    });
    const addBtn = container.createEl("button", {
      text: "+ \u6DFB\u52A0\u7C7B\u522B",
      cls: "mod-cta"
    });
    addBtn.addEventListener("click", async () => {
      this.plugin.settings.categories.push({
        name: "\u65B0\u7C7B\u522B",
        color: "#6366f1"
      });
      await this.plugin.saveSettings();
      this.renderCategories(container);
    });
  }
};

// src/utils.ts
var MINUTES_PER_DAY = 24 * 60;
var MAX_OVERNIGHT_HOURS = 16;
function formatTime(minutes) {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}`;
}
function formatDuration(minutes) {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h > 0 && m > 0)
    return `${h}\u5C0F\u65F6${m}\u5206\u949F`;
  if (h > 0)
    return `${h}\u5C0F\u65F6`;
  if (m > 0)
    return `${m}\u5206\u949F`;
  return "0\u5206\u949F";
}
function getCategoryColor(category, categories, uncategorizedColor) {
  const found = categories.find((c) => c.name === category);
  return found ? found.color : uncategorizedColor;
}
function buildCategoryColorMap(categories, uncategorizedColor) {
  const map = /* @__PURE__ */ new Map();
  for (const cat of categories) {
    map.set(cat.name, cat.color);
  }
  map.set("\u672A\u5206\u7C7B", uncategorizedColor);
  return map;
}
function computeDuration(start, end) {
  if (end < start) {
    const duration = MINUTES_PER_DAY - start + end;
    if (duration > MAX_OVERNIGHT_HOURS * 60)
      return 0;
    return duration;
  }
  return end - start;
}
function isValidTime(hours, minutes) {
  return hours >= 0 && hours <= 23 && minutes >= 0 && minutes <= 59;
}
var DEBUG = true;
function debugLog(...args) {
  if (DEBUG) {
    console.log("[TimelineDiary]", ...args);
  }
}

// src/parser.ts
function timeToMinutes(timeStr) {
  const parts = timeStr.split(":").map(Number);
  if (parts.length !== 2 || parts.some(isNaN)) {
    return { minutes: 0, valid: false };
  }
  const [hours, minutes] = parts;
  if (!isValidTime(hours, minutes)) {
    return { minutes: 0, valid: false };
  }
  return { minutes: hours * 60 + minutes, valid: true };
}
function parseTimeline(text, categoryNames) {
  const entries = [];
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed)
      continue;
    const match = trimmed.match(/^(\d{1,2}:\d{2})\s*-\s*(\d{1,2}:\d{2})\s+(.*?)(?:\s+#(\S+))?$/);
    if (!match)
      continue;
    const startResult = timeToMinutes(match[1]);
    const endResult = timeToMinutes(match[2]);
    if (!startResult.valid || !endResult.valid)
      continue;
    const description = match[3].trim();
    const tag = match[4];
    const duration = computeDuration(startResult.minutes, endResult.minutes);
    if (duration <= 0)
      continue;
    let category = "\u672A\u5206\u7C7B";
    if (tag) {
      category = categoryNames.includes(tag) ? tag : tag;
    }
    entries.push({
      start: startResult.minutes,
      end: endResult.minutes,
      description,
      category,
      duration
    });
  }
  return entries.sort((a, b) => a.start - b.start);
}

// src/renderer.ts
function renderDailyBar(entries, container, categories, uncategorizedColor) {
  const bar = container.createDiv("timeline-diary-bar");
  for (const entry of entries) {
    const segment = bar.createDiv("timeline-diary-bar-segment");
    const widthPercent = entry.duration / MINUTES_PER_DAY * 100;
    segment.style.width = `${widthPercent}%`;
    segment.style.backgroundColor = getCategoryColor(entry.category, categories, uncategorizedColor);
    const tooltip = segment.createDiv("timeline-diary-tooltip");
    tooltip.setText(
      `${formatTime(entry.start)} - ${formatTime(entry.end)} \xB7 ${entry.description} \xB7 ${formatDuration(entry.duration)}`
    );
  }
  if (entries.length === 0) {
    bar.style.background = "var(--background-modifier-border)";
    bar.createEl("span", {
      text: "\u6682\u65E0\u65F6\u95F4\u8F74\u6570\u636E",
      cls: "timeline-diary-empty-state"
    });
  }
}
function renderTimelineDetail(entries, container, categories, uncategorizedColor) {
  const detail = container.createDiv("timeline-diary-detail");
  for (const entry of entries) {
    const item = detail.createDiv("timeline-diary-detail-item");
    const colorStrip = item.createDiv("timeline-diary-detail-color");
    colorStrip.style.backgroundColor = getCategoryColor(entry.category, categories, uncategorizedColor);
    item.createDiv({
      cls: "timeline-diary-detail-time",
      text: `${formatTime(entry.start)} - ${formatTime(entry.end)}`
    });
    item.createDiv({
      cls: "timeline-diary-detail-text",
      text: entry.description
    });
    item.createDiv({
      cls: "timeline-diary-detail-tag",
      text: entry.category
    });
  }
}
function renderDailyTimeline(entries, container, categories, uncategorizedColor) {
  const wrapper = container.createDiv("timeline-diary-block");
  renderDailyBar(entries, wrapper, categories, uncategorizedColor);
  renderTimelineDetail(entries, wrapper, categories, uncategorizedColor);
}

// src/collector.ts
var TimelineCollector = class {
  constructor(vault, codeblockLang, categoryNames, diaryFolder) {
    this.cache = /* @__PURE__ */ new Map();
    this.vault = vault;
    this.codeblockLang = codeblockLang;
    this.categoryNames = categoryNames;
    this.diaryFolder = diaryFolder;
    this.codeblockRegex = this.buildRegex(codeblockLang);
  }
  updateConfig(codeblockLang, categoryNames, diaryFolder) {
    this.codeblockLang = codeblockLang;
    this.categoryNames = categoryNames;
    this.diaryFolder = diaryFolder;
    this.codeblockRegex = this.buildRegex(codeblockLang);
    this.cache.clear();
  }
  buildRegex(lang) {
    const escaped = lang.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return new RegExp("```" + escaped + "\\s*[\\r\\n]+([\\s\\S]*?)```", "g");
  }
  async collectAll() {
    var _a;
    const result = /* @__PURE__ */ new Map();
    const folder = this.vault.getAbstractFileByPath(this.diaryFolder);
    if (!folder) {
      debugLog("ERROR: folder not found:", this.diaryFolder);
      return result;
    }
    const folderPrefix = this.diaryFolder.replace(/\/$/, "") + "/";
    const files = this.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(folderPrefix)
    );
    const fileResults = await Promise.all(
      files.map((f) => this.parseFile(f))
    );
    for (let i = 0; i < files.length; i++) {
      const entries = fileResults[i];
      if (entries.length === 0)
        continue;
      const dateKey = (_a = this.cache.get(files[i].path)) == null ? void 0 : _a.dateKey;
      if (!dateKey)
        continue;
      const existing = result.get(dateKey);
      if (existing) {
        existing.push(...entries);
      } else {
        result.set(dateKey, entries);
      }
    }
    return result;
  }
  async parseFile(file) {
    const stat = await this.vault.adapter.stat(file.path);
    const mtime = stat ? stat.mtime : 0;
    const cached = this.cache.get(file.path);
    if (cached && cached.mtime === mtime) {
      return cached.entries;
    }
    const content = await this.vault.cachedRead(file);
    const entries = this.extractFromContent(content);
    const dateKey = this.extractDateFromFile(file);
    this.cache.set(file.path, { mtime, entries, dateKey: dateKey || "" });
    return entries;
  }
  extractFromContent(content) {
    const entries = [];
    let match;
    this.codeblockRegex.lastIndex = 0;
    while ((match = this.codeblockRegex.exec(content)) !== null) {
      const blockContent = match[1];
      const parsed = parseTimeline(blockContent, this.categoryNames);
      entries.push(...parsed);
    }
    return entries;
  }
  extractDateFromFile(file) {
    const basename = file.basename;
    const sepMatch = basename.match(/(\d{2,4})[.\-_](\d{1,2})[.\-_](\d{1,2})/);
    if (sepMatch) {
      return this.normalizeDate(sepMatch[1], sepMatch[2], sepMatch[3]);
    }
    const compact8 = basename.match(/(\d{4})(\d{2})(\d{2})/);
    if (compact8) {
      return this.normalizeDate(compact8[1], compact8[2], compact8[3]);
    }
    const compact6 = basename.match(/^(\d{2})(\d{2})(\d{2})$/);
    if (compact6) {
      return this.normalizeDate(compact6[1], compact6[2], compact6[3]);
    }
    return null;
  }
  normalizeDate(yearStr, monthStr, dayStr) {
    let year = parseInt(yearStr, 10);
    const month = parseInt(monthStr, 10);
    const day = parseInt(dayStr, 10);
    if (year < 100)
      year += 2e3;
    if (month < 1 || month > 12)
      return null;
    if (day < 1 || day > 31)
      return null;
    return `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
  }
};

// src/views/stats-view.ts
var import_obsidian2 = require("obsidian");
var STATS_VIEW_TYPE = "timeline-diary-stats";
var TimelineDiaryStatsView = class extends import_obsidian2.ItemView {
  constructor(leaf, settings, collector) {
    super(leaf);
    this.currentMode = "week";
    this.abortController = null;
    this.settings = settings;
    this.collector = collector;
    this.currentDate = (0, import_obsidian2.moment)();
  }
  getViewType() {
    return STATS_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u65F6\u95F4\u7EDF\u8BA1";
  }
  getIcon() {
    return "calendar-days";
  }
  async onOpen() {
    await this.render();
  }
  async onClose() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = null;
    this.containerEl.empty();
  }
  async render() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
    this.abortController = new AbortController();
    const { signal } = this.abortController;
    this.contentEl.empty();
    this.contentEl.addClass("timeline-diary-stats-view");
    const momentUnit = this.currentMode;
    const allData = await this.collector.collectAll();
    const categoryColorMap = buildCategoryColorMap(
      this.settings.categories,
      this.settings.uncategorizedColor
    );
    if (signal.aborted)
      return;
    const toolbar = this.contentEl.createDiv("timeline-diary-stats-toolbar");
    const weekBtn = toolbar.createEl("button", { text: "\u5468\u89C6\u56FE" });
    weekBtn.toggleClass("is-active", this.currentMode === "week");
    weekBtn.addEventListener("click", () => {
      this.currentMode = "week";
      this.render();
    });
    const monthBtn = toolbar.createEl("button", { text: "\u6708\u89C6\u56FE" });
    monthBtn.toggleClass("is-active", this.currentMode === "month");
    monthBtn.addEventListener("click", () => {
      this.currentMode = "month";
      this.render();
    });
    const prevBtn = toolbar.createEl("button", { text: "\u2190" });
    prevBtn.addEventListener("click", () => {
      this.currentDate.subtract(1, momentUnit);
      this.render();
    });
    const nextBtn = toolbar.createEl("button", { text: "\u2192" });
    nextBtn.addEventListener("click", () => {
      this.currentDate.add(1, momentUnit);
      this.render();
    });
    const todayBtn = toolbar.createEl("button", { text: "\u4ECA\u5929" });
    todayBtn.addEventListener("click", () => {
      this.currentDate = (0, import_obsidian2.moment)();
      this.render();
    });
    const dateLabel = toolbar.createEl("span", {
      text: this.currentDate.format(this.currentMode === "week" ? "YYYY\u5E74\u7B2Cw\u5468" : "YYYY\u5E74M\u6708")
    });
    dateLabel.style.marginLeft = "auto";
    dateLabel.style.fontWeight = "600";
    dateLabel.style.color = "var(--text-normal)";
    let totalEntries = 0;
    allData.forEach((entries) => {
      totalEntries += entries.length;
    });
    const diag = toolbar.createEl("span", {
      text: `\u6587\u4EF6: ${allData.size}\u5929, ${totalEntries}\u6761`
    });
    diag.style.fontSize = "11px";
    diag.style.color = "var(--text-faint)";
    diag.style.marginLeft = "8px";
    if (this.currentMode === "week") {
      this.renderWeekView(allData, categoryColorMap);
    } else {
      this.renderMonthView(allData, categoryColorMap);
    }
  }
  renderWeekView(allData, colorMap) {
    const weekStart = this.currentDate.clone().startOf("week");
    const container = this.contentEl.createDiv("timeline-diary-week-view");
    for (let i = 0; i < 7; i++) {
      const day = weekStart.clone().add(i, "days");
      const dateKey = day.format("YYYY-MM-DD");
      const entries = allData.get(dateKey) || [];
      const column = container.createDiv("timeline-diary-week-column");
      column.createDiv({ cls: "timeline-diary-week-label", text: day.format("ddd") });
      column.createDiv({ cls: "timeline-diary-week-date", text: day.format("MM-DD") });
      const bar = column.createDiv("timeline-diary-week-column-bar");
      this.renderEntrySegments(entries, bar, "timeline-diary-week-segment", colorMap);
    }
  }
  renderMonthView(allData, colorMap) {
    const monthStart = this.currentDate.clone().startOf("month");
    const monthEnd = this.currentDate.clone().endOf("month");
    const startDay = monthStart.clone().startOf("week");
    const endDay = monthEnd.clone().endOf("week");
    const container = this.contentEl.createDiv("timeline-diary-month-view");
    const headers = ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
    for (const h of headers) {
      container.createDiv({ cls: "timeline-diary-month-header-cell", text: h });
    }
    let currentDay = startDay.clone();
    while (currentDay.isSameOrBefore(endDay)) {
      const dateKey = currentDay.format("YYYY-MM-DD");
      const entries = allData.get(dateKey) || [];
      const isCurrentMonth = currentDay.isSame(monthStart, "month");
      const cell = container.createDiv("timeline-diary-month-cell");
      if (!isCurrentMonth) {
        cell.addClass("empty");
      }
      cell.createDiv({ cls: "timeline-diary-month-cell-date", text: currentDay.format("D") });
      if (entries.length > 0) {
        const bar = cell.createDiv("timeline-diary-month-cell-bar");
        this.renderEntrySegments(entries, bar, "timeline-diary-month-segment", colorMap);
      }
      currentDay.add(1, "day");
    }
  }
  renderEntrySegments(entries, bar, segmentClass, colorMap) {
    if (entries.length === 0) {
      bar.style.background = "var(--background-modifier-border)";
      bar.createEl("span", {
        text: "\u65E0",
        cls: "timeline-diary-empty-state"
      });
      return;
    }
    for (const entry of entries) {
      const segment = bar.createDiv(segmentClass);
      const heightPercent = entry.duration / MINUTES_PER_DAY * 100;
      segment.style.height = `${heightPercent}%`;
      segment.style.backgroundColor = colorMap.get(entry.category) || this.settings.uncategorizedColor;
      const tooltip = segment.createDiv("timeline-diary-tooltip");
      tooltip.setText(
        `${formatTime(entry.start)} - ${formatTime(entry.end)} \xB7 ${entry.description}`
      );
    }
  }
};

// main.ts
var TimelineDiaryPlugin = class extends import_obsidian3.Plugin {
  get categoryNames() {
    return this.settings.categories.map((c) => c.name);
  }
  async onload() {
    await this.loadSettings();
    this.collector = new TimelineCollector(
      this.app.vault,
      this.settings.codeblockLang,
      this.categoryNames,
      this.settings.diaryFolder
    );
    this.registerMarkdownCodeBlockProcessor(
      this.settings.codeblockLang,
      (source, el) => {
        const entries = parseTimeline(source, this.categoryNames);
        renderDailyTimeline(
          entries,
          el,
          this.settings.categories,
          this.settings.uncategorizedColor
        );
      }
    );
    this.registerView(STATS_VIEW_TYPE, (leaf) => {
      return new TimelineDiaryStatsView(
        leaf,
        this.settings,
        this.collector
      );
    });
    this.addCommand({
      id: "open-timeline-diary-stats",
      name: "\u6253\u5F00\u65F6\u95F4\u7EDF\u8BA1",
      callback: () => this.openStatsView()
    });
    this.addSettingTab(new TimelineDiarySettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(STATS_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    const oldLang = this.settings.codeblockLang;
    const oldCategories = this.settings.categories;
    const oldFolder = this.settings.diaryFolder;
    await this.saveData(this.settings);
    if (this.collector) {
      const catNamesChanged = oldCategories.length !== this.settings.categories.length || oldCategories.some(
        (c, i) => {
          var _a;
          return c.name !== ((_a = this.settings.categories[i]) == null ? void 0 : _a.name);
        }
      );
      if (oldLang !== this.settings.codeblockLang || catNamesChanged || oldFolder !== this.settings.diaryFolder) {
        this.collector.updateConfig(
          this.settings.codeblockLang,
          this.categoryNames,
          this.settings.diaryFolder
        );
      }
    }
  }
  async openStatsView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(STATS_VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: STATS_VIEW_TYPE,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
